### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by m-bystrova** [m-bystrova/learning#3]
- [ ] push module with AppConfig
- [ ] links to prepare for OCA (8/11(?))
- [ ] prepare list with courses on Spring/Spring Boot
  - [x] @m-bystrova 
  - [ ] @maximchukmm

- [x] @m-bystrova investigate coworkings

**Comment by m-bystrova** [comment]
From LinkedIn:
- [Become a Spring Developer ](https://www.linkedin.com/learning/paths/become-a-spring-developer?trk=learning-serp_learning-search-card_search-card&upsellOrderOrigin=default_guest_learning)
- [Spring: Spring MVC ](https://www.linkedin.com/learning/spring-spring-mvc-2?trk=learning-serp_learning-search-card_search-card&upsellOrderOrigin=default_guest_learning)
- [Spring: Test-Driven Development with JUnit ](https://www.linkedin.com/learning/spring-test-driven-development-with-junit?trk=learning-serp_learning-search-card_search-card&upsellOrderOrigin=default_guest_learning)

@maximchukmm, maybe you will be interested:
 [Advance Your Spring Development Skills](https://www.linkedin.com/learning/paths/advance-your-spring-development-skills?trk=learning-serp_learning-search-card_search-card&upsellOrderOrigin=default_guest_learning)

**Comment by m-bystrova** [comment]
that's funny:
- stepik [Spring для начинающих](https://stepik.org/course/115372/promo)
- udemy [Spring для начинающих](https://www.udemy.com/course/spring-framework/)

**Comment by m-bystrova** [comment]
Coursera
- [Spring Framework Specialization](https://www.coursera.org/specializations/spring-framework)

not online course
- [sysout](https://sysout.ru/spring/)

**Comment by m-bystrova** [comment]
baeldung:

- [Learn Spring 5 and Spring Boot 2](https://www.baeldung.com/learn-spring-course)
- [Learn Spring Data JPA](https://www.baeldung.com/learn-spring-data-jpa-course)
- [Build Your REST API with Spring﻿﻿﻿﻿﻿﻿ 5](https://www.baeldung.com/rest-with-spring-course) (low priority)

**Comment by maximchukmm** [comment]
About this one
[Spring: Test-Driven Development with JUnit](https://www.linkedin.com/learning/spring-test-driven-development-with-junit?trk=learning-serp_learning-search-card_search-card&upsellOrderOrigin=default_guest_learning)

I have an access to this - let's consider it - in my view it's one of the best courses about this topic:
https://rieckpil.de/courses/testing-spring-boot-applications-masterclass/

**Comment by maximchukmm** [comment]
Another good start about Spring by Evgeny Borisov:
https://www.youtube.com/playlist?list=PL6yLoZ_3Y0HKGL3F7vv2SNSrA3TkbXtBX

Can discuss which videos to study - as the first step while I am checking what edu platforms are available for us.

**Comment by m-bystrova** [comment]
OCA Java SE 8:
https://github.com/arjspe/boekjes

**Comment by maximchukmm** [comment]
> OCA Java SE 8: https://github.com/arjspe/boekjes
Don't want to waste time on Java 8 certification - Java 11 as minimum.

**Comment by maximchukmm** [comment]
@m-bystrova can we close this issue?
