### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by m-bystrova** [m-bystrova/learning#5]
Четная неделя:
**ср**: _Clean code_ 2 главы **или** 1 глава и сертификация
**пт**: _Java by Comparison_ 1 глава 

Нечетная неделя:
**ср**: Борисов, потом заменяется pet-проектом
**пт**: курс со [степика](https://stepik.org/course/115372/promo), можно начать раньше, т.к. первые несколько лекций доступны

**Comment by maximchukmm** [comment]
- [ ] let's discuss this plan today on our call. And if you want, we can use Russian, but in my view it's better to use in this repository only English.

**Comment by maximchukmm** [comment]
@m-bystrova this issue can be closed, I guess. wdyt?
